
import React, { useState, useEffect, useMemo } from 'react';
import { Plus, StickyNote, X, Save, Trash2, Calendar, Edit3, Share2, BookOpen, Download, UserCheck, GraduationCap } from 'lucide-react';
import { Note, User, Student } from '../types';
import { storageService } from '../services/storageService';

interface NotesManagerProps {
  user: User;
}

const NotesManager: React.FC<NotesManagerProps> = ({ user }) => {
  const [activeTab, setActiveTab] = useState<'private' | 'class'>('private');
  const [notes, setNotes] = useState<Note[]>([]);
  const [isFormOpen, setIsFormOpen] = useState(false);
  const [editingNote, setEditingNote] = useState<Note | null>(null);
  
  const [formData, setFormData] = useState({ 
    title: '', 
    content: '', 
    isClassNote: false, 
    targetGrade: '5th' 
  });

  const students = useMemo(() => storageService.getStudents(), []);
  const currentUserStudent = useMemo(() => 
    user.role === 'student' ? students.find(s => s.id === user.linkedId) : null
  , [user, students]);

  useEffect(() => {
    setNotes(storageService.getNotes(user.id, user.role, currentUserStudent?.grade));
  }, [user.id, user.role, currentUserStudent]);

  const handleSaveNote = (e: React.FormEvent) => {
    e.preventDefault();
    const newNote: Note = {
      id: editingNote ? editingNote.id : Math.random().toString(36).substr(2, 9),
      userId: user.id,
      title: formData.title,
      content: formData.content,
      date: new Date().toLocaleDateString(),
      color: editingNote?.color || ['bg-blue-50', 'bg-purple-50', 'bg-amber-50', 'bg-emerald-50', 'bg-rose-50'][Math.floor(Math.random() * 5)],
      isClassNote: formData.isClassNote,
      targetGrade: formData.isClassNote ? formData.targetGrade : undefined,
      authorName: formData.isClassNote ? user.name : undefined
    };

    storageService.saveNote(newNote);
    setNotes(storageService.getNotes(user.id, user.role, currentUserStudent?.grade));
    setIsFormOpen(false);
    setEditingNote(null);
    setFormData({ title: '', content: '', isClassNote: false, targetGrade: '5th' });
  };

  const handleDelete = (id: string) => {
    if (window.confirm('Delete this note?')) {
      storageService.deleteNote(id);
      setNotes(storageService.getNotes(user.id, user.role, currentUserStudent?.grade));
    }
  };

  const handleEdit = (note: Note) => {
    setEditingNote(note);
    setFormData({ 
      title: note.title, 
      content: note.content, 
      isClassNote: !!note.isClassNote, 
      targetGrade: note.targetGrade || '5th' 
    });
    setIsFormOpen(true);
  };

  const downloadNote = (note: Note) => {
    const fileContent = `
Title: ${note.title}
Date: ${note.date}
Author: ${note.authorName || 'Personal Note'}
Target Grade: ${note.targetGrade || 'Private'}
--------------------------------------------------

${note.content}

--------------------------------------------------
Generated by Manikgad CBSE Portal
    `.trim();

    const blob = new Blob([fileContent], { type: 'text/plain' });
    const url = window.URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `${note.title.replace(/\s+/g, '_')}_StudyNote.txt`;
    document.body.appendChild(a);
    a.click();
    window.URL.revokeObjectURL(url);
    document.body.removeChild(a);
  };

  const privateNotes = notes.filter(n => !n.isClassNote);
  const classNotes = notes.filter(n => n.isClassNote);
  
  const displayNotes = activeTab === 'private' ? privateNotes : classNotes;
  const isStaff = user.role === 'teacher' || user.role === 'owner';

  const grades = ['5th', '6th', '7th', '8th', '9th', '10th'];

  return (
    <div className="space-y-8 animate-in fade-in duration-500">
      <div className="flex flex-col md:flex-row md:items-center justify-between gap-4">
        <div>
          <h2 className="text-2xl font-black text-gray-900 tracking-tight flex items-center gap-2">
            <StickyNote className="w-7 h-7 text-amber-500" />
            Study Notes & Resources
          </h2>
          <p className="text-gray-500 text-sm mt-1">Manage personal scribbles and class-wide study materials.</p>
        </div>
        {isStaff && (
          <button 
            onClick={() => setIsFormOpen(true)}
            className="flex items-center gap-2 px-6 py-3 bg-blue-600 text-white rounded-2xl font-bold hover:bg-blue-700 transition-all shadow-lg shadow-blue-500/20"
          >
            <Plus className="w-5 h-5" />
            Upload Study Note
          </button>
        )}
      </div>

      {/* Navigation Tabs */}
      <div className="flex bg-gray-100 p-1 rounded-2xl w-fit">
        <button 
          onClick={() => setActiveTab('private')}
          className={`flex items-center gap-2 px-6 py-2.5 rounded-xl text-xs font-black uppercase tracking-widest transition-all ${activeTab === 'private' ? 'bg-white text-blue-600 shadow-sm' : 'text-gray-400 hover:text-gray-600'}`}
        >
          <UserCheck className="w-4 h-4" />
          My Private Notes
        </button>
        <button 
          onClick={() => setActiveTab('class')}
          className={`flex items-center gap-2 px-6 py-2.5 rounded-xl text-xs font-black uppercase tracking-widest transition-all ${activeTab === 'class' ? 'bg-white text-blue-600 shadow-sm' : 'text-gray-400 hover:text-gray-600'}`}
        >
          <BookOpen className="w-4 h-4" />
          {user.role === 'student' ? 'Class Resources' : 'Shared with Classes'}
        </button>
      </div>

      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
        {displayNotes.length > 0 ? displayNotes.map(note => (
          <div key={note.id} className={`${note.color || 'bg-white'} p-6 rounded-[2.5rem] border border-gray-100 shadow-sm relative group hover:shadow-md transition-all flex flex-col min-h-[220px]`}>
            <div className="flex items-start justify-between mb-4">
              <div className="flex-1 min-w-0">
                <div className="flex items-center gap-2 mb-1">
                  {note.isClassNote && <GraduationCap className="w-3.5 h-3.5 text-blue-600" />}
                  <h3 className="font-black text-gray-900 truncate pr-4">{note.title}</h3>
                </div>
                {note.isClassNote && (
                  <span className="text-[9px] font-black text-blue-600 bg-blue-100/50 px-2 py-0.5 rounded uppercase tracking-tighter">
                    Std {note.targetGrade} Resource
                  </span>
                )}
              </div>
              <div className="flex gap-1">
                {/* Download only for class notes or as a feature for all */}
                <button 
                  onClick={() => downloadNote(note)} 
                  className="p-2 hover:bg-black/5 rounded-full transition-colors text-gray-500 hover:text-blue-600"
                  title="Download as Text"
                >
                  <Download className="w-4 h-4" />
                </button>
                
                {/* Edit/Delete only for author */}
                {note.userId === user.id && (
                  <>
                    <button onClick={() => handleEdit(note)} className="p-2 hover:bg-black/5 rounded-full transition-colors">
                      <Edit3 className="w-4 h-4 text-gray-600" />
                    </button>
                    <button onClick={() => handleDelete(note.id)} className="p-2 hover:bg-red-500/10 rounded-full transition-colors">
                      <Trash2 className="w-4 h-4 text-red-500" />
                    </button>
                  </>
                )}
              </div>
            </div>
            
            <p className="text-sm text-gray-700 leading-relaxed mb-6 whitespace-pre-wrap line-clamp-4 flex-1">
              {note.content}
            </p>
            
            <div className="flex items-center justify-between mt-auto">
              <div className="flex items-center gap-2 text-[10px] font-black text-gray-400 uppercase tracking-widest">
                <Calendar className="w-3 h-3" />
                {note.date}
              </div>
              {note.authorName && (
                <div className="text-[10px] font-black text-gray-400 uppercase italic">
                  By {note.authorName}
                </div>
              )}
            </div>
          </div>
        )) : (
          <div className="col-span-full py-20 bg-white rounded-[2.5rem] border-2 border-dashed border-gray-100 flex flex-col items-center justify-center text-center px-10">
            <div className="w-20 h-20 bg-gray-50 rounded-full flex items-center justify-center mb-4">
              {activeTab === 'private' ? <StickyNote className="w-10 h-10 text-gray-200" /> : <BookOpen className="w-10 h-10 text-gray-200" />}
            </div>
            <h3 className="text-xl font-bold text-gray-900">
              {activeTab === 'private' ? 'No private notes yet' : 'No class resources found'}
            </h3>
            <p className="text-gray-500 mt-2 max-w-sm">
              {activeTab === 'private' 
                ? 'Use notes to organize your study material or homework tasks.' 
                : user.role === 'student' 
                  ? 'Your teachers haven\'t uploaded any shared study materials for your grade yet.'
                  : 'Start sharing study materials with your students by clicking the "Upload" button.'}
            </p>
          </div>
        )}
      </div>

      {isFormOpen && (
        <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-gray-900/40 backdrop-blur-sm animate-in fade-in duration-300">
          <div className="bg-white w-full max-w-xl rounded-[2.5rem] shadow-2xl overflow-hidden animate-in zoom-in duration-300">
            <div className="p-8">
              <div className="flex items-center justify-between mb-8">
                <h3 className="text-2xl font-black text-gray-900">
                  {editingNote ? 'Edit Note' : 'Create Note'}
                </h3>
                <button onClick={() => { setIsFormOpen(false); setEditingNote(null); setFormData({ title: '', content: '', isClassNote: false, targetGrade: '5th' }); }} className="p-2 hover:bg-gray-100 rounded-full transition-colors">
                  <X className="w-6 h-6 text-gray-400" />
                </button>
              </div>
              
              <form onSubmit={handleSaveNote} className="space-y-6">
                <div className="space-y-2">
                  <label className="text-xs font-black text-gray-400 uppercase tracking-widest ml-1">Title</label>
                  <input 
                    required
                    type="text"
                    value={formData.title}
                    onChange={e => setFormData({ ...formData, title: e.target.value })}
                    className="w-full p-4 bg-gray-50 border border-gray-100 rounded-2xl focus:ring-4 focus:ring-blue-500/10 focus:bg-white outline-none transition-all font-bold text-gray-900"
                    placeholder="E.g. Mathematics Formulas"
                  />
                </div>
                
                <div className="space-y-2">
                  <label className="text-xs font-black text-gray-400 uppercase tracking-widest ml-1">Content</label>
                  <textarea 
                    required
                    rows={6}
                    value={formData.content}
                    onChange={e => setFormData({ ...formData, content: e.target.value })}
                    className="w-full p-4 bg-gray-50 border border-gray-100 rounded-2xl focus:ring-4 focus:ring-blue-500/10 focus:bg-white outline-none transition-all font-medium text-gray-700 resize-none"
                    placeholder="Start typing your note here..."
                  />
                </div>

                {isStaff && (
                  <div className="p-6 bg-blue-50 rounded-3xl border border-blue-100 space-y-4">
                    <div className="flex items-center justify-between">
                      <div className="flex items-center gap-2">
                        <Share2 className="w-4 h-4 text-blue-600" />
                        <span className="text-sm font-bold text-blue-900">Share with Class?</span>
                      </div>
                      <button 
                        type="button"
                        onClick={() => setFormData({...formData, isClassNote: !formData.isClassNote})}
                        className={`w-12 h-6 rounded-full transition-all relative ${formData.isClassNote ? 'bg-blue-600' : 'bg-gray-300'}`}
                      >
                        <div className={`absolute top-1 w-4 h-4 bg-white rounded-full transition-all ${formData.isClassNote ? 'left-7' : 'left-1'}`} />
                      </button>
                    </div>
                    
                    {formData.isClassNote && (
                      <div className="space-y-2 animate-in slide-in-from-top-2 duration-300">
                        <label className="text-[10px] font-black text-blue-400 uppercase tracking-widest ml-1">Target Standard</label>
                        <select 
                          className="w-full p-3 bg-white border border-blue-100 rounded-xl outline-none font-bold text-blue-700"
                          value={formData.targetGrade}
                          onChange={e => setFormData({...formData, targetGrade: e.target.value})}
                        >
                          {grades.map(g => (
                            <option key={g} value={g}>{g} Standard</option>
                          ))}
                        </select>
                        <p className="text-[10px] text-blue-400 italic">This note will be visible to all students in {formData.targetGrade} Standard.</p>
                      </div>
                    )}
                  </div>
                )}
                
                <button 
                  type="submit"
                  className="w-full py-4 bg-blue-600 text-white rounded-2xl font-black text-lg shadow-xl shadow-blue-500/20 hover:bg-blue-700 transition-all flex items-center justify-center gap-2"
                >
                  <Save className="w-5 h-5" />
                  {editingNote ? 'Update Note' : 'Create & Save'}
                </button>
              </form>
            </div>
          </div>
        </div>
      )}
    </div>
  );
};

export default NotesManager;
